[build]
  publish = "./dist/"
  command = "npx --no-install elm-tooling install && npm run build"

[build.environment]
  ELM_HOME = "$NETLIFY_BUILD_BASE/cache/elm"
  NO_ELM_TOOLING_INSTALL = "1"
  NODE_VERSION = "14.18.1"
